import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const repoRoot = process.cwd();

describe("public post consumers", () => {
	// Source guard: verifies that every page which lists posts goes through getAllPosts,
	// which is the only entry point that applies the draft-exclusion env gate.
	// Replacing this with a runtime check would require a full Astro build.
	it("routes public-facing post lookups through the shared helper", () => {
		for (const relativePath of [
			"src/pages/writing/index.astro",
			"src/components/SeriesPanel.astro",
		]) {
			const source = fs.readFileSync(path.join(repoRoot, relativePath), "utf8");

			expect(source).toContain("getAllPosts");
			expect(source).not.toMatch(/getCollection\((["'])post\1\)/);
		}
	});
});

describe("page header markup", () => {
	// Source guard: Astro's set:html behaves differently on <p> vs <div> — wrapping
	// inside an existing <p> produces double-wrapped paragraphs in the rendered HTML.
	// The rendered output is only observable via a full Astro build.
	it("does not wrap rendered html fragments in paragraph tags", () => {
		const source = fs.readFileSync(path.join(repoRoot, "src/components/PageHeader.astro"), "utf8");

		expect(source).not.toContain("<p set:html={processedDescription}");
		expect(source).not.toContain("<p set:html={processedAdditionalInfo}");
		expect(source).toContain("<div set:html={processedDescription} />");
		expect(source).toContain("<div set:html={processedAdditionalInfo} />");
	});
});

describe("public link hygiene", () => {
	// Source guard: the sitemap route is generated by @astrojs/sitemap at a specific
	// path; /sitemap.xml and /privacy do not exist as generated routes. A link to the
	// wrong path silently 404s in production.
	it("does not point footer utility links at missing generated routes", () => {
		const source = fs.readFileSync(
			path.join(repoRoot, "src/components/layout/Footer.astro"),
			"utf8",
		);

		expect(source).not.toContain('href="/privacy"');
		expect(source).not.toContain('href="/sitemap.xml"');
		expect(source).toContain('href="/sitemap-index.xml"');
	});

	// Source guard: the archive page must filter tag categories to only those with a
	// generated /tags/[tag] route. Without the filter, topic links would 404 for any
	// tag that appears in configuration but has no matching posts.
	it("filters archive topic links to generated tag routes", () => {
		const source = fs.readFileSync(path.join(repoRoot, "src/pages/posts/archive.astro"), "utf8");

		expect(source).toContain("const visibleTagCategories = Object.entries(tagCategories)");
		expect(source).toContain("tags: tags.filter((tag) => uniqueTags.includes(tag))");
		expect(source).toContain("visibleTagCategories.map");
		expect(source).not.toContain("Object.entries(tagCategories).map(([category, tags])");
	});

	// Regression guards for specific bad link patterns that were introduced in content
	// edits and subsequently fixed. Asserting on the raw markdown source is intentional:
	// the link syntax (the destination string) is what the build tool sees, and
	// character-level heuristics on rendered HTML would produce false positives given
	// that some posts legitimately document raw markdown syntax as examples.
	it("does not contain known malformed public content links", () => {
		const checkedFiles = [
			"src/content/post/industrial-policy-a-round-up-of-historical-case-studies-and-beyond.md",
			"src/content/writing/a-flight-plan-that-fails-boston-review.md",
			"src/content/post/transfonter.md",
		];
		const source = checkedFiles
			.map((relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8"))
			.join("\n");

		expect(source).not.toContain("https://doi.org/https://doi.org/");
		expect(source).not.toContain("(walkerhanlon.com/papers/hanlon_shipbuilding.pdf)");
		expect(source).not.toContain("(eh.net/eha/images/blog/Lane.pdf)");
		expect(source).not.toContain("(www.giorcellimichela.com/");
		expect(source).not.toContain("]((https://www.bostonreview.net/");
		expect(source).not.toContain("](posts/social-image/)");
		expect(source).toContain("(https://walkerhanlon.com/papers/hanlon_shipbuilding.pdf)");
		expect(source).toContain("(https://eh.net/eha/images/blog/Lane.pdf)");
		expect(source).toContain("(https://www.giorcellimichela.com/");
		expect(source).toContain("](/posts/social-image/)");
	});

	// Regression guards for relative or root-relative paths that silently produce 404s
	// under Astro's file-based routing. Same rationale as above for using raw source.
	it("does not contain known rendered links to missing local routes", () => {
		const checkedFiles = [
			"src/content/post/lane-docs/comprehensive-site-maintenance.md",
			"src/content/post/remark-rehype.md",
		];
		const source = checkedFiles
			.map((relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8"))
			.join("\n");

		expect(source).not.toContain("](./seo-structured-data-maintenance)");
		expect(source).not.toContain("](./adding-documentation-pages)");
		expect(source).not.toContain("](./design-system)");
		expect(source).not.toContain("[license]: license");
		expect(source).toContain("](/posts/lane-docs/seo-structured-data-maintenance/)");
		expect(source).toContain("](/posts/lane-docs/adding-docs-guide/)");
		expect(source).toContain("](/posts/lane-docs/design-system/)");
		expect(source).toContain(
			"[license]: https://github.com/remarkjs/remark-rehype/blob/main/license",
		);
	});
});

describe("verification command wiring", () => {
	it("keeps live smoke checking both the canonical site and the Pages origin policy", () => {
		const packageJson = JSON.parse(
			fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"),
		) as {
			scripts?: Record<string, string>;
		};

		expect(packageJson.scripts?.["smoke:prod"]).toBe(
			"node scripts/validation/smoke-test.mjs https://nathanlane.info",
		);
		expect(packageJson.scripts?.["smoke:pages"]).toBe(
			"node scripts/validation/pages-origin-redirect-smoke.mjs",
		);
		expect(packageJson.scripts?.["smoke:live"]).toBe("pnpm run smoke:prod && pnpm run smoke:pages");
	});
});
