# Site Settings
baseurl: 		""
title: 			Land Labor Capital - Nathan Lane, Ph.D. Candidate.

name: 			Land Labor Capital
description: 	A beautifully contemporary and elegant Jekyll theme
url: 			"http://localhost:4000"

paginate: 		20
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			hello@indiqo.eu

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Indiqo.	

# Build Settings
permalinks: 	pretty
highlighter:    pygments
gems: [jekyll-paginate]
