# Site Settings
baseurl: 		""
title: 			Nathan Lane - Ph.D. Candidate

name: 			Nathan Lane <i> Ph.D. Candidate, Economics</i>
description: 	Nathan Lane - Ph.D. Candidate, Economics IIES-Sweden
url: 			"http://localhost:4000"

paginate: 		30
paginate_path: 	"blog/page:num"

markdown: redcarpet

twitter: 		straightedge
email: 			nathaniel.lane@iies.su.se

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2016-2014 Nathaniel Lane.	

# Build Settings
permalinks: 	pretty