# Site Settings
title: 			Nathaniel Lane
safe: true
lsi: false
name: 			Nathaniel Lane
description: Nathaniel Lane
baseurl:     ""


gems: [jekyll-paginate]

kramdown:
  input: GFM
  hard_wrap: false

paginate: 		30
paginate_path: 	"blog/page:num"

<<<<<<< HEAD
markdown: kramdown

highlighter: rouge
=======
incremental: false
highlighter: rouge
gist:
  noscript: false
   
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: mathjax  
>>>>>>> b03c493249fb5e513e4054cc026a20154dbba8bb

twitter: 		straightedge
email: 			nathaniel.lane@iies.su.se

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2017-2014 Nathaniel Lane.	

# Build Settings
permalinks: 	pretty

