# Site Settings
title: 			Nathaniel Lane
safe: true
lsi: false
name: 			Nathaniel Lane
description: Nathaniel Lane
baseurl:     ""


gems: [jekyll-paginate]

kramdown:
  input: GFM
  hard_wrap: false

paginate: 		30
paginate_path: 	"blog/page:num"


markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: mathjax  

incremental: false
highlighter: rouge
gist:
  noscript: false

twitter: 		straightedge
email: 			nathaniel.lane@iies.su.se

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2017-2014 Nathaniel Lane.	

# Build Settings
permalinks: 	pretty

