---
title: Nathaniel Lane
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
safe: true
lsi: false
name: Nathaniel Lane
description: Nathaniel Lane
baseurl: ''
exclude:
- vendor
gems:
- jekyll-paginate
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: mathjax
paginate: 30
paginate_path: blog/page:num
image: header-1.png
markdown: kramdown
highlighter: rouge
incremental: false
gist:
  noscript: false
twitter: straightedge
email: nlane@mit.edu
copyright: Copyright 2018-2014 Nathaniel Lane.
permalinks: pretty
