# Site Settings
baseurl: 		""
title: 			"Nathaniel Lane, Ph.D. Candidate"
safe: true
lsi: false
name: 			"Nathaniel Lane"
description: "Nathaniel Lane, Ph.D. Candidate"

paginate: 		30
paginate_path: 	"blog/page:num"

incremental: false
highlighter: rouge
gist:
  noscript: false
   
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: mathjax  

twitter: 		straightedge
email: 			nathaniel.lane@iies.su.se

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2016-2014 Nathaniel Lane.	

# Build Settings
permalinks: 	pretty