title: Nathan Lane - nathanlane.github.io
author: Dr. Nathan Lane
email: nathaniel.lane@monash.edu
description: >-
  The personal webpage of Assistant Professor/Lecturer, Nathaniel Lane.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nathanlane.info" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus
  - jekyll-assets
  - jekyll-paginate

assets:
  prefix: "/assets"
  sources:
      -   _assets/css
      -   _assets/img


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
