<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="">
    <title>Nathan Lane - nathanlane.github.io</title>
    <meta name="author" content="Dr. Nathan Lane">
    <meta name="description" content="The personal webpage of Assistant Professor/Lecturer, Nathaniel Lane.">
    <link rel="stylesheet" href="/main.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Karla:300,400,700">
</head>
<body>

<!-- Add your site or application content here -->
<p>---
title: Nathan Lane - nathanlane.github.io
author: Dr. Nathan Lane
email: nathaniel.lane@monash.edu
description: The personal webpage of Assistant Professor/Lecturer, Nathaniel Lane.
baseurl: ''
url: http://www.nathanlane.info
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
- jekyll-assets
- jekyll-paginate
assets:
  prefix: "/assets"
  sources:
  - _assets/css
  - _assets/img
timezone: Etc/UTC
</p>

  </body>
</html>